const menuFilter = {
    "id": 18,
    "groupNm": "신규_지역",
    "sort": 1,
    "categories": [{
        "id": 556,
        "groupId": 18,
        "sort": 1,
        "fullCode": "01",
        "depth": 1,
        "selected": false,
        "children": [{
            "id": 557,
            "groupId": 18,
            "sort": 1,
            "fullCode": "01",
            "depth": 2,
            "selected": false,
            "children": [],
            "name": "전체",
            "__i__": 0,
            "__first__": true,
            "__last__": false
        }, {
            "id": 570,
            "groupId": 18,
            "sort": 102,
            "fullCode": "0102",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 571,
                "groupId": 18,
                "sort": 102,
                "fullCode": "0102",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 572,
                "groupId": 18,
                "sort": 10202,
                "fullCode": "010202",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 573,
                "groupId": 18,
                "sort": 10203,
                "fullCode": "010203",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 574,
                "groupId": 18,
                "sort": 10204,
                "fullCode": "010204",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 575,
                "groupId": 18,
                "sort": 10205,
                "fullCode": "010205",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 576,
                "groupId": 18,
                "sort": 10206,
                "fullCode": "010206",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 577,
                "groupId": 18,
                "sort": 10207,
                "fullCode": "010207",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 578,
                "groupId": 18,
                "sort": 10208,
                "fullCode": "010208",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 579,
                "groupId": 18,
                "sort": 10209,
                "fullCode": "010209",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 580,
                "groupId": 18,
                "sort": 10210,
                "fullCode": "010210",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 581,
                "groupId": 18,
                "sort": 10211,
                "fullCode": "010211",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 582,
                "groupId": 18,
                "sort": 10212,
                "fullCode": "010212",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "강동/강남",
            "__i__": 1,
            "__first__": false,
            "__last__": false
        }, {
            "id": 583,
            "groupId": 18,
            "sort": 103,
            "fullCode": "0103",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 584,
                "groupId": 18,
                "sort": 103,
                "fullCode": "0103",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 585,
                "groupId": 18,
                "sort": 10302,
                "fullCode": "010302",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 586,
                "groupId": 18,
                "sort": 10303,
                "fullCode": "010303",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 587,
                "groupId": 18,
                "sort": 10304,
                "fullCode": "010304",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 588,
                "groupId": 18,
                "sort": 10305,
                "fullCode": "010305",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 589,
                "groupId": 18,
                "sort": 10306,
                "fullCode": "010306",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 590,
                "groupId": 18,
                "sort": 10307,
                "fullCode": "010307",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 591,
                "groupId": 18,
                "sort": 10308,
                "fullCode": "010308",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 592,
                "groupId": 18,
                "sort": 10309,
                "fullCode": "010309",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 593,
                "groupId": 18,
                "sort": 10310,
                "fullCode": "010310",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 594,
                "groupId": 18,
                "sort": 10311,
                "fullCode": "010311",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 595,
                "groupId": 18,
                "sort": 10312,
                "fullCode": "010312",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "강서/강북",
            "__i__": 2,
            "__first__": false,
            "__last__": true
        }],
        "name": "서울",
        "href": "?categoryIds=556,557",
        "__i__": 0,
        "__first__": true,
        "__last__": false
    }, {
        "id": 596,
        "groupId": 18,
        "sort": 2,
        "fullCode": "02",
        "depth": 1,
        "selected": false,
        "children": [{
            "id": 597,
            "groupId": 18,
            "sort": 2,
            "fullCode": "02",
            "depth": 2,
            "selected": false,
            "children": [],
            "name": "전체",
            "__i__": 0,
            "__first__": true,
            "__last__": false
        }, {
            "id": 610,
            "groupId": 18,
            "sort": 202,
            "fullCode": "0202",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 611,
                "groupId": 18,
                "sort": 202,
                "fullCode": "0202",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 612,
                "groupId": 18,
                "sort": 20202,
                "fullCode": "020202",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 613,
                "groupId": 18,
                "sort": 20203,
                "fullCode": "020203",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 614,
                "groupId": 18,
                "sort": 20204,
                "fullCode": "020204",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 615,
                "groupId": 18,
                "sort": 20205,
                "fullCode": "020205",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 616,
                "groupId": 18,
                "sort": 20206,
                "fullCode": "020206",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 617,
                "groupId": 18,
                "sort": 20207,
                "fullCode": "020207",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 618,
                "groupId": 18,
                "sort": 20208,
                "fullCode": "020208",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 619,
                "groupId": 18,
                "sort": 20209,
                "fullCode": "020209",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 620,
                "groupId": 18,
                "sort": 20210,
                "fullCode": "020210",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 621,
                "groupId": 18,
                "sort": 20211,
                "fullCode": "020211",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 622,
                "groupId": 18,
                "sort": 20212,
                "fullCode": "020212",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "일산/파주/헤이리",
            "__i__": 1,
            "__first__": false,
            "__last__": false
        }, {
            "id": 623,
            "groupId": 18,
            "sort": 203,
            "fullCode": "0203",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 624,
                "groupId": 18,
                "sort": 203,
                "fullCode": "0203",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 625,
                "groupId": 18,
                "sort": 20302,
                "fullCode": "020302",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 626,
                "groupId": 18,
                "sort": 20303,
                "fullCode": "020303",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 627,
                "groupId": 18,
                "sort": 20304,
                "fullCode": "020304",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 628,
                "groupId": 18,
                "sort": 20305,
                "fullCode": "020305",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 629,
                "groupId": 18,
                "sort": 20306,
                "fullCode": "020306",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 630,
                "groupId": 18,
                "sort": 20307,
                "fullCode": "020307",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 631,
                "groupId": 18,
                "sort": 20308,
                "fullCode": "020308",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 632,
                "groupId": 18,
                "sort": 20309,
                "fullCode": "020309",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 633,
                "groupId": 18,
                "sort": 20310,
                "fullCode": "020310",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 634,
                "groupId": 18,
                "sort": 20311,
                "fullCode": "020311",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 635,
                "groupId": 18,
                "sort": 20312,
                "fullCode": "020312",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "가평/양평",
            "__i__": 2,
            "__first__": false,
            "__last__": false
        }, {
            "id": 636,
            "groupId": 18,
            "sort": 204,
            "fullCode": "0204",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 637,
                "groupId": 18,
                "sort": 204,
                "fullCode": "0204",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 638,
                "groupId": 18,
                "sort": 20402,
                "fullCode": "020402",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 639,
                "groupId": 18,
                "sort": 20403,
                "fullCode": "020403",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 640,
                "groupId": 18,
                "sort": 20404,
                "fullCode": "020404",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 641,
                "groupId": 18,
                "sort": 20405,
                "fullCode": "020405",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 642,
                "groupId": 18,
                "sort": 20406,
                "fullCode": "020406",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 643,
                "groupId": 18,
                "sort": 20407,
                "fullCode": "020407",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 644,
                "groupId": 18,
                "sort": 20408,
                "fullCode": "020408",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 645,
                "groupId": 18,
                "sort": 20409,
                "fullCode": "020409",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 646,
                "groupId": 18,
                "sort": 20410,
                "fullCode": "020410",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 647,
                "groupId": 18,
                "sort": 20411,
                "fullCode": "020411",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 648,
                "groupId": 18,
                "sort": 20412,
                "fullCode": "020412",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "구리/남양주/포천",
            "__i__": 3,
            "__first__": false,
            "__last__": false
        }, {
            "id": 649,
            "groupId": 18,
            "sort": 205,
            "fullCode": "0205",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 650,
                "groupId": 18,
                "sort": 205,
                "fullCode": "0205",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 651,
                "groupId": 18,
                "sort": 20502,
                "fullCode": "020502",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 652,
                "groupId": 18,
                "sort": 20503,
                "fullCode": "020503",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 653,
                "groupId": 18,
                "sort": 20504,
                "fullCode": "020504",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 654,
                "groupId": 18,
                "sort": 20505,
                "fullCode": "020505",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 655,
                "groupId": 18,
                "sort": 20506,
                "fullCode": "020506",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 656,
                "groupId": 18,
                "sort": 20507,
                "fullCode": "020507",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 657,
                "groupId": 18,
                "sort": 20508,
                "fullCode": "020508",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 658,
                "groupId": 18,
                "sort": 20509,
                "fullCode": "020509",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 659,
                "groupId": 18,
                "sort": 20510,
                "fullCode": "020510",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 660,
                "groupId": 18,
                "sort": 20511,
                "fullCode": "020511",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 661,
                "groupId": 18,
                "sort": 20512,
                "fullCode": "020512",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "용인/이천/판교",
            "__i__": 4,
            "__first__": false,
            "__last__": false
        }, {
            "id": 662,
            "groupId": 18,
            "sort": 206,
            "fullCode": "0206",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 663,
                "groupId": 18,
                "sort": 206,
                "fullCode": "0206",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 664,
                "groupId": 18,
                "sort": 20602,
                "fullCode": "020602",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 665,
                "groupId": 18,
                "sort": 20603,
                "fullCode": "020603",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 666,
                "groupId": 18,
                "sort": 20604,
                "fullCode": "020604",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 667,
                "groupId": 18,
                "sort": 20605,
                "fullCode": "020605",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 668,
                "groupId": 18,
                "sort": 20606,
                "fullCode": "020606",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 669,
                "groupId": 18,
                "sort": 20607,
                "fullCode": "020607",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 670,
                "groupId": 18,
                "sort": 20608,
                "fullCode": "020608",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 671,
                "groupId": 18,
                "sort": 20609,
                "fullCode": "020609",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 672,
                "groupId": 18,
                "sort": 20610,
                "fullCode": "020610",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 673,
                "groupId": 18,
                "sort": 20611,
                "fullCode": "020611",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 674,
                "groupId": 18,
                "sort": 20612,
                "fullCode": "020612",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "수원/평택",
            "__i__": 5,
            "__first__": false,
            "__last__": false
        }, {
            "id": 675,
            "groupId": 18,
            "sort": 207,
            "fullCode": "0207",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 676,
                "groupId": 18,
                "sort": 207,
                "fullCode": "0207",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 677,
                "groupId": 18,
                "sort": 20702,
                "fullCode": "020702",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 678,
                "groupId": 18,
                "sort": 20703,
                "fullCode": "020703",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 679,
                "groupId": 18,
                "sort": 20704,
                "fullCode": "020704",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 680,
                "groupId": 18,
                "sort": 20705,
                "fullCode": "020705",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 681,
                "groupId": 18,
                "sort": 20706,
                "fullCode": "020706",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 682,
                "groupId": 18,
                "sort": 20707,
                "fullCode": "020707",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 683,
                "groupId": 18,
                "sort": 20708,
                "fullCode": "020708",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 684,
                "groupId": 18,
                "sort": 20709,
                "fullCode": "020709",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 685,
                "groupId": 18,
                "sort": 20710,
                "fullCode": "020710",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 686,
                "groupId": 18,
                "sort": 20711,
                "fullCode": "020711",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 687,
                "groupId": 18,
                "sort": 20712,
                "fullCode": "020712",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "인천/부천/강화",
            "__i__": 6,
            "__first__": false,
            "__last__": true
        }],
        "name": "경기/인천",
        "__i__": 1,
        "__first__": false,
        "__last__": false
    }, {
        "id": 688,
        "groupId": 18,
        "sort": 3,
        "fullCode": "03",
        "depth": 1,
        "selected": false,
        "children": [{
            "id": 689,
            "groupId": 18,
            "sort": 3,
            "fullCode": "03",
            "depth": 2,
            "selected": false,
            "children": [],
            "name": "전체",
            "__i__": 0,
            "__first__": true,
            "__last__": false
        }, {
            "id": 702,
            "groupId": 18,
            "sort": 302,
            "fullCode": "0302",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 703,
                "groupId": 18,
                "sort": 302,
                "fullCode": "0302",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 704,
                "groupId": 18,
                "sort": 30202,
                "fullCode": "030202",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 705,
                "groupId": 18,
                "sort": 30203,
                "fullCode": "030203",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 706,
                "groupId": 18,
                "sort": 30204,
                "fullCode": "030204",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 707,
                "groupId": 18,
                "sort": 30205,
                "fullCode": "030205",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 708,
                "groupId": 18,
                "sort": 30206,
                "fullCode": "030206",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 709,
                "groupId": 18,
                "sort": 30207,
                "fullCode": "030207",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 710,
                "groupId": 18,
                "sort": 30208,
                "fullCode": "030208",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 711,
                "groupId": 18,
                "sort": 30209,
                "fullCode": "030209",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 712,
                "groupId": 18,
                "sort": 30210,
                "fullCode": "030210",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 713,
                "groupId": 18,
                "sort": 30211,
                "fullCode": "030211",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 714,
                "groupId": 18,
                "sort": 30212,
                "fullCode": "030212",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "평창",
            "__i__": 1,
            "__first__": false,
            "__last__": false
        }, {
            "id": 715,
            "groupId": 18,
            "sort": 303,
            "fullCode": "0303",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 716,
                "groupId": 18,
                "sort": 303,
                "fullCode": "0303",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 717,
                "groupId": 18,
                "sort": 30302,
                "fullCode": "030302",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 718,
                "groupId": 18,
                "sort": 30303,
                "fullCode": "030303",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 719,
                "groupId": 18,
                "sort": 30304,
                "fullCode": "030304",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 720,
                "groupId": 18,
                "sort": 30305,
                "fullCode": "030305",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 721,
                "groupId": 18,
                "sort": 30306,
                "fullCode": "030306",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 722,
                "groupId": 18,
                "sort": 30307,
                "fullCode": "030307",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 723,
                "groupId": 18,
                "sort": 30308,
                "fullCode": "030308",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 724,
                "groupId": 18,
                "sort": 30309,
                "fullCode": "030309",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 725,
                "groupId": 18,
                "sort": 30310,
                "fullCode": "030310",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 726,
                "groupId": 18,
                "sort": 30311,
                "fullCode": "030311",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 727,
                "groupId": 18,
                "sort": 30312,
                "fullCode": "030312",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "춘천/홍천",
            "__i__": 2,
            "__first__": false,
            "__last__": false
        }, {
            "id": 728,
            "groupId": 18,
            "sort": 304,
            "fullCode": "0304",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 729,
                "groupId": 18,
                "sort": 304,
                "fullCode": "0304",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 730,
                "groupId": 18,
                "sort": 30402,
                "fullCode": "030402",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 731,
                "groupId": 18,
                "sort": 30403,
                "fullCode": "030403",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 732,
                "groupId": 18,
                "sort": 30404,
                "fullCode": "030404",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 733,
                "groupId": 18,
                "sort": 30405,
                "fullCode": "030405",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 734,
                "groupId": 18,
                "sort": 30406,
                "fullCode": "030406",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 735,
                "groupId": 18,
                "sort": 30407,
                "fullCode": "030407",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 736,
                "groupId": 18,
                "sort": 30408,
                "fullCode": "030408",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 737,
                "groupId": 18,
                "sort": 30409,
                "fullCode": "030409",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 738,
                "groupId": 18,
                "sort": 30410,
                "fullCode": "030410",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 739,
                "groupId": 18,
                "sort": 30411,
                "fullCode": "030411",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 740,
                "groupId": 18,
                "sort": 30412,
                "fullCode": "030412",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "정선/영월",
            "__i__": 3,
            "__first__": false,
            "__last__": false
        }, {
            "id": 741,
            "groupId": 18,
            "sort": 305,
            "fullCode": "0305",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 742,
                "groupId": 18,
                "sort": 305,
                "fullCode": "0305",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 743,
                "groupId": 18,
                "sort": 30502,
                "fullCode": "030502",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 744,
                "groupId": 18,
                "sort": 30503,
                "fullCode": "030503",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 745,
                "groupId": 18,
                "sort": 30504,
                "fullCode": "030504",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 746,
                "groupId": 18,
                "sort": 30505,
                "fullCode": "030505",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 747,
                "groupId": 18,
                "sort": 30506,
                "fullCode": "030506",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 748,
                "groupId": 18,
                "sort": 30507,
                "fullCode": "030507",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 749,
                "groupId": 18,
                "sort": 30508,
                "fullCode": "030508",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 750,
                "groupId": 18,
                "sort": 30509,
                "fullCode": "030509",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 751,
                "groupId": 18,
                "sort": 30510,
                "fullCode": "030510",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 752,
                "groupId": 18,
                "sort": 30511,
                "fullCode": "030511",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 753,
                "groupId": 18,
                "sort": 30512,
                "fullCode": "030512",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "속초/강릉",
            "__i__": 4,
            "__first__": false,
            "__last__": true
        }],
        "name": "강원",
        "__i__": 2,
        "__first__": false,
        "__last__": false
    }, {
        "id": 754,
        "groupId": 18,
        "sort": 4,
        "fullCode": "04",
        "depth": 1,
        "selected": false,
        "children": [{
            "id": 755,
            "groupId": 18,
            "sort": 4,
            "fullCode": "04",
            "depth": 2,
            "selected": false,
            "children": [],
            "name": "전체",
            "__i__": 0,
            "__first__": true,
            "__last__": false
        }, {
            "id": 768,
            "groupId": 18,
            "sort": 402,
            "fullCode": "0402",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 769,
                "groupId": 18,
                "sort": 402,
                "fullCode": "0402",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 770,
                "groupId": 18,
                "sort": 40202,
                "fullCode": "040202",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 771,
                "groupId": 18,
                "sort": 40203,
                "fullCode": "040203",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 772,
                "groupId": 18,
                "sort": 40204,
                "fullCode": "040204",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 773,
                "groupId": 18,
                "sort": 40205,
                "fullCode": "040205",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 774,
                "groupId": 18,
                "sort": 40206,
                "fullCode": "040206",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 775,
                "groupId": 18,
                "sort": 40207,
                "fullCode": "040207",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 776,
                "groupId": 18,
                "sort": 40208,
                "fullCode": "040208",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 777,
                "groupId": 18,
                "sort": 40209,
                "fullCode": "040209",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 778,
                "groupId": 18,
                "sort": 40210,
                "fullCode": "040210",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 779,
                "groupId": 18,
                "sort": 40211,
                "fullCode": "040211",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 780,
                "groupId": 18,
                "sort": 40212,
                "fullCode": "040212",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "태안/대천",
            "__i__": 1,
            "__first__": false,
            "__last__": false
        }, {
            "id": 781,
            "groupId": 18,
            "sort": 403,
            "fullCode": "0403",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 782,
                "groupId": 18,
                "sort": 403,
                "fullCode": "0403",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 783,
                "groupId": 18,
                "sort": 40302,
                "fullCode": "040302",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 784,
                "groupId": 18,
                "sort": 40303,
                "fullCode": "040303",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 785,
                "groupId": 18,
                "sort": 40304,
                "fullCode": "040304",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 786,
                "groupId": 18,
                "sort": 40305,
                "fullCode": "040305",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 787,
                "groupId": 18,
                "sort": 40306,
                "fullCode": "040306",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 788,
                "groupId": 18,
                "sort": 40307,
                "fullCode": "040307",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 789,
                "groupId": 18,
                "sort": 40308,
                "fullCode": "040308",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 790,
                "groupId": 18,
                "sort": 40309,
                "fullCode": "040309",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 791,
                "groupId": 18,
                "sort": 40310,
                "fullCode": "040310",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 792,
                "groupId": 18,
                "sort": 40311,
                "fullCode": "040311",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 793,
                "groupId": 18,
                "sort": 40312,
                "fullCode": "040312",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "단양/제천",
            "__i__": 2,
            "__first__": false,
            "__last__": false
        }, {
            "id": 794,
            "groupId": 18,
            "sort": 404,
            "fullCode": "0404",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 795,
                "groupId": 18,
                "sort": 404,
                "fullCode": "0404",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 796,
                "groupId": 18,
                "sort": 40402,
                "fullCode": "040402",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 797,
                "groupId": 18,
                "sort": 40403,
                "fullCode": "040403",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 798,
                "groupId": 18,
                "sort": 40404,
                "fullCode": "040404",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 799,
                "groupId": 18,
                "sort": 40405,
                "fullCode": "040405",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 800,
                "groupId": 18,
                "sort": 40406,
                "fullCode": "040406",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 801,
                "groupId": 18,
                "sort": 40407,
                "fullCode": "040407",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 802,
                "groupId": 18,
                "sort": 40408,
                "fullCode": "040408",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 803,
                "groupId": 18,
                "sort": 40409,
                "fullCode": "040409",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 804,
                "groupId": 18,
                "sort": 40410,
                "fullCode": "040410",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 805,
                "groupId": 18,
                "sort": 40411,
                "fullCode": "040411",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 806,
                "groupId": 18,
                "sort": 40412,
                "fullCode": "040412",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "대전",
            "__i__": 3,
            "__first__": false,
            "__last__": true
        }],
        "name": "충청",
        "__i__": 3,
        "__first__": false,
        "__last__": false
    }, {
        "id": 807,
        "groupId": 18,
        "sort": 5,
        "fullCode": "05",
        "depth": 1,
        "selected": false,
        "children": [{
            "id": 808,
            "groupId": 18,
            "sort": 5,
            "fullCode": "05",
            "depth": 2,
            "selected": false,
            "children": [],
            "name": "전체",
            "__i__": 0,
            "__first__": true,
            "__last__": false
        }, {
            "id": 821,
            "groupId": 18,
            "sort": 502,
            "fullCode": "0502",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 822,
                "groupId": 18,
                "sort": 502,
                "fullCode": "0502",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 823,
                "groupId": 18,
                "sort": 50202,
                "fullCode": "050202",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 824,
                "groupId": 18,
                "sort": 50203,
                "fullCode": "050203",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 825,
                "groupId": 18,
                "sort": 50204,
                "fullCode": "050204",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 826,
                "groupId": 18,
                "sort": 50205,
                "fullCode": "050205",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 827,
                "groupId": 18,
                "sort": 50206,
                "fullCode": "050206",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 828,
                "groupId": 18,
                "sort": 50207,
                "fullCode": "050207",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 829,
                "groupId": 18,
                "sort": 50208,
                "fullCode": "050208",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 830,
                "groupId": 18,
                "sort": 50209,
                "fullCode": "050209",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 831,
                "groupId": 18,
                "sort": 50210,
                "fullCode": "050210",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 832,
                "groupId": 18,
                "sort": 50211,
                "fullCode": "050211",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 833,
                "groupId": 18,
                "sort": 50212,
                "fullCode": "050212",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "부산",
            "__i__": 1,
            "__first__": false,
            "__last__": false
        }, {
            "id": 834,
            "groupId": 18,
            "sort": 503,
            "fullCode": "0503",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 835,
                "groupId": 18,
                "sort": 503,
                "fullCode": "0503",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 836,
                "groupId": 18,
                "sort": 50302,
                "fullCode": "050302",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 837,
                "groupId": 18,
                "sort": 50303,
                "fullCode": "050303",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 838,
                "groupId": 18,
                "sort": 50304,
                "fullCode": "050304",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 839,
                "groupId": 18,
                "sort": 50305,
                "fullCode": "050305",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 840,
                "groupId": 18,
                "sort": 50306,
                "fullCode": "050306",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 841,
                "groupId": 18,
                "sort": 50307,
                "fullCode": "050307",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 842,
                "groupId": 18,
                "sort": 50308,
                "fullCode": "050308",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 843,
                "groupId": 18,
                "sort": 50309,
                "fullCode": "050309",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 844,
                "groupId": 18,
                "sort": 50310,
                "fullCode": "050310",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 845,
                "groupId": 18,
                "sort": 50311,
                "fullCode": "050311",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 846,
                "groupId": 18,
                "sort": 50312,
                "fullCode": "050312",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "경주",
            "__i__": 2,
            "__first__": false,
            "__last__": false
        }, {
            "id": 847,
            "groupId": 18,
            "sort": 504,
            "fullCode": "0504",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 848,
                "groupId": 18,
                "sort": 504,
                "fullCode": "0504",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 849,
                "groupId": 18,
                "sort": 50402,
                "fullCode": "050402",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 850,
                "groupId": 18,
                "sort": 50403,
                "fullCode": "050403",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 851,
                "groupId": 18,
                "sort": 50404,
                "fullCode": "050404",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 852,
                "groupId": 18,
                "sort": 50405,
                "fullCode": "050405",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 853,
                "groupId": 18,
                "sort": 50406,
                "fullCode": "050406",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 854,
                "groupId": 18,
                "sort": 50407,
                "fullCode": "050407",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 855,
                "groupId": 18,
                "sort": 50408,
                "fullCode": "050408",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 856,
                "groupId": 18,
                "sort": 50409,
                "fullCode": "050409",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 857,
                "groupId": 18,
                "sort": 50410,
                "fullCode": "050410",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 858,
                "groupId": 18,
                "sort": 50411,
                "fullCode": "050411",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 859,
                "groupId": 18,
                "sort": 50412,
                "fullCode": "050412",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "대구",
            "__i__": 3,
            "__first__": false,
            "__last__": false
        }, {
            "id": 860,
            "groupId": 18,
            "sort": 505,
            "fullCode": "0505",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 861,
                "groupId": 18,
                "sort": 505,
                "fullCode": "0505",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 862,
                "groupId": 18,
                "sort": 50502,
                "fullCode": "050502",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 863,
                "groupId": 18,
                "sort": 50503,
                "fullCode": "050503",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 864,
                "groupId": 18,
                "sort": 50504,
                "fullCode": "050504",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 865,
                "groupId": 18,
                "sort": 50505,
                "fullCode": "050505",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 866,
                "groupId": 18,
                "sort": 50506,
                "fullCode": "050506",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 867,
                "groupId": 18,
                "sort": 50507,
                "fullCode": "050507",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 868,
                "groupId": 18,
                "sort": 50508,
                "fullCode": "050508",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 869,
                "groupId": 18,
                "sort": 50509,
                "fullCode": "050509",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 870,
                "groupId": 18,
                "sort": 50510,
                "fullCode": "050510",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 871,
                "groupId": 18,
                "sort": 50511,
                "fullCode": "050511",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 872,
                "groupId": 18,
                "sort": 50512,
                "fullCode": "050512",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "남해",
            "__i__": 4,
            "__first__": false,
            "__last__": false
        }, {
            "id": 873,
            "groupId": 18,
            "sort": 506,
            "fullCode": "0506",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 874,
                "groupId": 18,
                "sort": 506,
                "fullCode": "0506",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 875,
                "groupId": 18,
                "sort": 50602,
                "fullCode": "050602",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 876,
                "groupId": 18,
                "sort": 50603,
                "fullCode": "050603",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 877,
                "groupId": 18,
                "sort": 50604,
                "fullCode": "050604",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 878,
                "groupId": 18,
                "sort": 50605,
                "fullCode": "050605",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 879,
                "groupId": 18,
                "sort": 50606,
                "fullCode": "050606",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 880,
                "groupId": 18,
                "sort": 50607,
                "fullCode": "050607",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 881,
                "groupId": 18,
                "sort": 50608,
                "fullCode": "050608",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 882,
                "groupId": 18,
                "sort": 50609,
                "fullCode": "050609",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 883,
                "groupId": 18,
                "sort": 50610,
                "fullCode": "050610",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 884,
                "groupId": 18,
                "sort": 50611,
                "fullCode": "050611",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 885,
                "groupId": 18,
                "sort": 50612,
                "fullCode": "050612",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "거제/통영",
            "__i__": 5,
            "__first__": false,
            "__last__": true
        }],
        "name": "경상",
        "__i__": 4,
        "__first__": false,
        "__last__": false
    }, {
        "id": 886,
        "groupId": 18,
        "sort": 6,
        "fullCode": "06",
        "depth": 1,
        "selected": false,
        "children": [{
            "id": 887,
            "groupId": 18,
            "sort": 6,
            "fullCode": "06",
            "depth": 2,
            "selected": false,
            "children": [],
            "name": "전체",
            "__i__": 0,
            "__first__": true,
            "__last__": false
        }, {
            "id": 900,
            "groupId": 18,
            "sort": 602,
            "fullCode": "0602",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 901,
                "groupId": 18,
                "sort": 602,
                "fullCode": "0602",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 902,
                "groupId": 18,
                "sort": 60202,
                "fullCode": "060202",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 903,
                "groupId": 18,
                "sort": 60203,
                "fullCode": "060203",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 904,
                "groupId": 18,
                "sort": 60204,
                "fullCode": "060204",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 905,
                "groupId": 18,
                "sort": 60205,
                "fullCode": "060205",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 906,
                "groupId": 18,
                "sort": 60206,
                "fullCode": "060206",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 907,
                "groupId": 18,
                "sort": 60207,
                "fullCode": "060207",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 908,
                "groupId": 18,
                "sort": 60208,
                "fullCode": "060208",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 909,
                "groupId": 18,
                "sort": 60209,
                "fullCode": "060209",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 910,
                "groupId": 18,
                "sort": 60210,
                "fullCode": "060210",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 911,
                "groupId": 18,
                "sort": 60211,
                "fullCode": "060211",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 912,
                "groupId": 18,
                "sort": 60212,
                "fullCode": "060212",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "여수",
            "__i__": 1,
            "__first__": false,
            "__last__": false
        }, {
            "id": 913,
            "groupId": 18,
            "sort": 603,
            "fullCode": "0603",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 914,
                "groupId": 18,
                "sort": 603,
                "fullCode": "0603",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 915,
                "groupId": 18,
                "sort": 60302,
                "fullCode": "060302",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 916,
                "groupId": 18,
                "sort": 60303,
                "fullCode": "060303",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 917,
                "groupId": 18,
                "sort": 60304,
                "fullCode": "060304",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 918,
                "groupId": 18,
                "sort": 60305,
                "fullCode": "060305",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 919,
                "groupId": 18,
                "sort": 60306,
                "fullCode": "060306",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 920,
                "groupId": 18,
                "sort": 60307,
                "fullCode": "060307",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 921,
                "groupId": 18,
                "sort": 60308,
                "fullCode": "060308",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 922,
                "groupId": 18,
                "sort": 60309,
                "fullCode": "060309",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 923,
                "groupId": 18,
                "sort": 60310,
                "fullCode": "060310",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 924,
                "groupId": 18,
                "sort": 60311,
                "fullCode": "060311",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 925,
                "groupId": 18,
                "sort": 60312,
                "fullCode": "060312",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "전주",
            "__i__": 2,
            "__first__": false,
            "__last__": false
        }, {
            "id": 926,
            "groupId": 18,
            "sort": 604,
            "fullCode": "0604",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 927,
                "groupId": 18,
                "sort": 604,
                "fullCode": "0604",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 928,
                "groupId": 18,
                "sort": 60402,
                "fullCode": "060402",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 929,
                "groupId": 18,
                "sort": 60403,
                "fullCode": "060403",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 930,
                "groupId": 18,
                "sort": 60404,
                "fullCode": "060404",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 931,
                "groupId": 18,
                "sort": 60405,
                "fullCode": "060405",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 932,
                "groupId": 18,
                "sort": 60406,
                "fullCode": "060406",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 933,
                "groupId": 18,
                "sort": 60407,
                "fullCode": "060407",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 934,
                "groupId": 18,
                "sort": 60408,
                "fullCode": "060408",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 935,
                "groupId": 18,
                "sort": 60409,
                "fullCode": "060409",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 936,
                "groupId": 18,
                "sort": 60410,
                "fullCode": "060410",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 937,
                "groupId": 18,
                "sort": 60411,
                "fullCode": "060411",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 938,
                "groupId": 18,
                "sort": 60412,
                "fullCode": "060412",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "무주",
            "__i__": 3,
            "__first__": false,
            "__last__": false
        }, {
            "id": 939,
            "groupId": 18,
            "sort": 605,
            "fullCode": "0605",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 940,
                "groupId": 18,
                "sort": 605,
                "fullCode": "0605",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 941,
                "groupId": 18,
                "sort": 60502,
                "fullCode": "060502",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 942,
                "groupId": 18,
                "sort": 60503,
                "fullCode": "060503",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 943,
                "groupId": 18,
                "sort": 60504,
                "fullCode": "060504",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 944,
                "groupId": 18,
                "sort": 60505,
                "fullCode": "060505",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 945,
                "groupId": 18,
                "sort": 60506,
                "fullCode": "060506",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 946,
                "groupId": 18,
                "sort": 60507,
                "fullCode": "060507",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 947,
                "groupId": 18,
                "sort": 60508,
                "fullCode": "060508",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 948,
                "groupId": 18,
                "sort": 60509,
                "fullCode": "060509",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 949,
                "groupId": 18,
                "sort": 60510,
                "fullCode": "060510",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 950,
                "groupId": 18,
                "sort": 60511,
                "fullCode": "060511",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 951,
                "groupId": 18,
                "sort": 60512,
                "fullCode": "060512",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "광주/화순/함평",
            "__i__": 4,
            "__first__": false,
            "__last__": false
        }, {
            "id": 952,
            "groupId": 18,
            "sort": 606,
            "fullCode": "0606",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 953,
                "groupId": 18,
                "sort": 606,
                "fullCode": "0606",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 954,
                "groupId": 18,
                "sort": 60602,
                "fullCode": "060602",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 955,
                "groupId": 18,
                "sort": 60603,
                "fullCode": "060603",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 956,
                "groupId": 18,
                "sort": 60604,
                "fullCode": "060604",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 957,
                "groupId": 18,
                "sort": 60605,
                "fullCode": "060605",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 958,
                "groupId": 18,
                "sort": 60606,
                "fullCode": "060606",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 959,
                "groupId": 18,
                "sort": 60607,
                "fullCode": "060607",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 960,
                "groupId": 18,
                "sort": 60608,
                "fullCode": "060608",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 961,
                "groupId": 18,
                "sort": 60609,
                "fullCode": "060609",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 962,
                "groupId": 18,
                "sort": 60610,
                "fullCode": "060610",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 963,
                "groupId": 18,
                "sort": 60611,
                "fullCode": "060611",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 964,
                "groupId": 18,
                "sort": 60612,
                "fullCode": "060612",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "담양/순천/보성",
            "__i__": 5,
            "__first__": false,
            "__last__": true
        }],
        "name": "전라",
        "__i__": 5,
        "__first__": false,
        "__last__": false
    }, {
        "id": 965,
        "groupId": 18,
        "sort": 7,
        "fullCode": "07",
        "depth": 1,
        "selected": false,
        "children": [{
            "id": 966,
            "groupId": 18,
            "sort": 7,
            "fullCode": "07",
            "depth": 2,
            "selected": false,
            "children": [],
            "name": "전체",
            "__i__": 0,
            "__first__": true,
            "__last__": false
        }, {
            "id": 979,
            "groupId": 18,
            "sort": 702,
            "fullCode": "0702",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 980,
                "groupId": 18,
                "sort": 702,
                "fullCode": "0702",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 981,
                "groupId": 18,
                "sort": 70202,
                "fullCode": "070202",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 982,
                "groupId": 18,
                "sort": 70203,
                "fullCode": "070203",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 983,
                "groupId": 18,
                "sort": 70204,
                "fullCode": "070204",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 984,
                "groupId": 18,
                "sort": 70205,
                "fullCode": "070205",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 985,
                "groupId": 18,
                "sort": 70206,
                "fullCode": "070206",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 986,
                "groupId": 18,
                "sort": 70207,
                "fullCode": "070207",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 987,
                "groupId": 18,
                "sort": 70208,
                "fullCode": "070208",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 988,
                "groupId": 18,
                "sort": 70209,
                "fullCode": "070209",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 989,
                "groupId": 18,
                "sort": 70210,
                "fullCode": "070210",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 990,
                "groupId": 18,
                "sort": 70211,
                "fullCode": "070211",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 991,
                "groupId": 18,
                "sort": 70212,
                "fullCode": "070212",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "제주시",
            "__i__": 1,
            "__first__": false,
            "__last__": false
        }, {
            "id": 992,
            "groupId": 18,
            "sort": 703,
            "fullCode": "0703",
            "depth": 2,
            "selected": false,
            "children": [{
                "id": 993,
                "groupId": 18,
                "sort": 703,
                "fullCode": "0703",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "전체"
            }, {
                "id": 994,
                "groupId": 18,
                "sort": 70302,
                "fullCode": "070302",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "워터파크"
            }, {
                "id": 995,
                "groupId": 18,
                "sort": 70303,
                "fullCode": "070303",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "테마파크"
            }, {
                "id": 996,
                "groupId": 18,
                "sort": 70304,
                "fullCode": "070304",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "키즈"
            }, {
                "id": 997,
                "groupId": 18,
                "sort": 70305,
                "fullCode": "070305",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "입장권"
            }, {
                "id": 998,
                "groupId": 18,
                "sort": 70306,
                "fullCode": "070306",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "레포츠"
            }, {
                "id": 999,
                "groupId": 18,
                "sort": 70307,
                "fullCode": "070307",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "체험/축제"
            }, {
                "id": 1000,
                "groupId": 18,
                "sort": 70308,
                "fullCode": "070308",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "공연/전시"
            }, {
                "id": 1001,
                "groupId": 18,
                "sort": 70309,
                "fullCode": "070309",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "호텔"
            }, {
                "id": 1002,
                "groupId": 18,
                "sort": 70310,
                "fullCode": "070310",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "리조트"
            }, {
                "id": 1003,
                "groupId": 18,
                "sort": 70311,
                "fullCode": "070311",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "펜션"
            }, {
                "id": 1004,
                "groupId": 18,
                "sort": 70312,
                "fullCode": "070312",
                "depth": 3,
                "selected": false,
                "children": [],
                "name": "이색숙박"
            }],
            "name": "서귀포시",
            "__i__": 2,
            "__first__": false,
            "__last__": true
        }],
        "name": "제주",
        "__i__": 6,
        "__first__": false,
        "__last__": true
    }],
    "groupCode": "region"
}
